package main

import (
	"bufio"
	"context"
	"crypto/rand"
	"flag"
	"fmt"
	"io"
	"log"
	"math/big"
	"net"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/gorilla/websocket"
)

const (
	defaultTimeout = 10 * time.Second
	defaultWorkers = 50
)

const (
	StatusAlive   = "ALIVE"
	StatusDead    = "DEAD"
	StatusInvalid = "INVALID"
)

type CheckResult struct {
	URL    string `json:"url"`
	Status string `json:"status"`
	PingMs *int64 `json:"ping_ms,omitempty"`
}

type TrackerHistory struct {
	Checks             uint64 `json:"checks"`
	AliveChecks        uint64 `json:"alive_checks"`
	FirstSeenTs        int64  `json:"first_seen_ts"`
	FirstAliveTs       int64  `json:"first_alive_ts"`
	LastSeenTs         int64  `json:"last_seen_ts"`
	LastAliveTs        int64  `json:"last_alive_ts"`
	StreakAliveStartTs int64  `json:"streak_alive_start_ts"`
}

var (
	trackerRe    = regexp.MustCompile(`(?i)(https?|udp|wss)://[^\s,]*?/announce`)
	httpClient   *http.Client
	peerIDPrefix string
)

func init() {
	peerIDPrefix = fmt.Sprintf("-RS0001-%s", randomNumeric(12))
	httpClient = &http.Client{
		Timeout: defaultTimeout,
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			return http.ErrUseLastResponse
		},
	}
}

func randomNumeric(n int) string {
	const digits = "0123456789"
	ret := make([]byte, n)
	for i := range ret {
		bi, err := rand.Int(rand.Reader, big.NewInt(int64(len(digits))))
		if err != nil {
			bi = big.NewInt(0)
		}
		ret[i] = digits[bi.Int64()]
	}
	return string(ret)
}

func parseTrackerLine(line string) string {
	line = strings.TrimSpace(line)
	if strings.HasPrefix(line, "[") && strings.Contains(line, "](") && strings.HasSuffix(line, ")") {
		_, after, found := strings.Cut(line, "](")
		if found {
			return strings.TrimSuffix(after, ")")
		}
	}
	return line
}

func collapsePathSlashes(path string) string {
	var out []rune
	prevSlash := false
	for _, ch := range path {
		if ch == '/' {
			if !prevSlash {
				out = append(out, ch)
			}
			prevSlash = true
		} else {
			out = append(out, ch)
			prevSlash = false
		}
	}
	if len(out) == 0 {
		return "/"
	}
	return string(out)
}


func bdecodeSimple(data []byte) bool {
	if len(data) == 0 || data[0] != 'd' {
		return false
	}
	keys := []string{"interval", "peers", "failure reason"}
	for _, k := range keys {
		if bytesContains(data, k) {
			return true
		}
	}
	return false
}

func normalizeTrackerURL(raw string) (string, error) {
	candidate := strings.Trim(raw, "\"'<>[](){};,.")
	u, err := url.Parse(candidate)
	if err != nil {
		return "", err
	}
	scheme := strings.ToLower(u.Scheme)
	if scheme != "http" && scheme != "https" && scheme != "udp" && scheme != "wss" {
		return "", fmt.Errorf("unsupported scheme")
	}
	host := u.Hostname()
	if host == "" {
		return "", fmt.Errorf("no host")
	}
	if ip := net.ParseIP(host); ip == nil && !strings.Contains(host, ".") {
		return "", fmt.Errorf("invalid host")
	}
	normalizedPath := collapsePathSlashes(u.Path)
	if !(strings.HasSuffix(normalizedPath, "/announce") ||
		strings.Contains(normalizedPath, "/announce?") ||
		strings.HasSuffix(normalizedPath, "/announce.php") ||
		strings.HasSuffix(normalizedPath, "/announce.jsp") ||
		strings.HasSuffix(normalizedPath, "/announce.aspx")) {
		return "", fmt.Errorf("path must be related to /announce")
	}
	u.Path = normalizedPath
	// 保留查询参数（如 passkey）
	u.Fragment = ""

	if (scheme == "http" && u.Port() == "80") || (scheme == "https" && u.Port() == "443") {
		if ip := net.ParseIP(host); ip != nil && ip.To4() == nil {
			// IPv6 地址：保留方括号
			u.Host = "[" + host + "]"
		} else {
			u.Host = host
		}
	}

	return u.String(), nil   // ← 补回这一行
}                            // ← 补回这一行

func bytesContains(data []byte, substr string) bool {
	return strings.Contains(string(data), substr)
}

func isParkedDomain(content []byte) bool {
	lower := strings.ToLower(string(content))
	indicators := []string{
		"domain for sale", "domain is for sale", "buy this domain",
		"domain expired", "domain has expired", "this domain is expired",
		"register this domain", "domain available", "parked domain",
		"domain parking", "coming soon", "under construction",
		"page not found", "404 not found", "namecheap",
		"godaddy parked", "sedo domain parking", "domain portfolio",
		"premium domain", "afternic", "escrow.com", "dan.com/buy-domain",
		"undeveloped", "this webpage was generated by the domain owner",
		"hugedomains.com", "bodis.com", "sedoparking",
	}
	for _, ind := range indicators {
		if strings.Contains(lower, ind) {
			return true
		}
	}
	head := string(content[:min(len(content), 500)])
	head = strings.ToLower(head)
	return strings.Contains(head, "<html") || strings.Contains(head, "<!doctype html")
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

func checkHTTP(ctx context.Context, tracker string) (string, *int64) {
    // 安全合并查询参数：先解析 tracker URL，然后用 tracker 原有参数与新参数合并
    base, err := url.Parse(tracker)
    if err != nil {
        return StatusInvalid, nil
    }
    // 构造所需参数
    baseParams := base.Query()
    baseParams.Set("info_hash", "00000000000000000000")
    baseParams.Set("peer_id", peerIDPrefix)
    baseParams.Set("port", "6881")
    baseParams.Set("uploaded", "0")
    baseParams.Set("downloaded", "0")
    baseParams.Set("left", "0")
    baseParams.Set("compact", "1")
    baseParams.Set("event", "started")
    base.RawQuery = baseParams.Encode()

    req, err := http.NewRequestWithContext(ctx, "GET", base.String(), nil)
    if err != nil {
        return StatusDead, nil
    }
    start := time.Now()
    resp, err := httpClient.Do(req)
    if err != nil {
        return StatusDead, nil
    }
    defer resp.Body.Close()
    elapsed := int64(time.Since(start).Milliseconds())
    body, err := io.ReadAll(io.LimitReader(resp.Body, 100*1024))
    if err != nil {
        return StatusDead, &elapsed
    }

    if isParkedDomain(body) {
        return StatusInvalid, &elapsed
    }
    if bdecodeSimple(body) {
        return StatusAlive, &elapsed
    }
    if resp.StatusCode == http.StatusOK {
        head := strings.ToLower(string(body[:min(len(body), 200)]))
        if strings.Contains(head, "<html") || strings.Contains(head, "<body") || strings.Contains(head, "<head") {
            return StatusInvalid, &elapsed
        }
        if len(body) > 50000 {
            return StatusInvalid, &elapsed
        }
        return StatusDead, &elapsed
    }
    if (resp.StatusCode == http.StatusBadRequest || resp.StatusCode == http.StatusForbidden) && bdecodeSimple(body) {
        return StatusAlive, &elapsed
    }
    return StatusDead, &elapsed
}

func checkUDP(ctx context.Context, tracker string) (string, *int64) {
	u, err := url.Parse(tracker)
	if err != nil {
		return StatusInvalid, nil
	}
	host := u.Hostname()
	port := u.Port()
	if port == "" {
		port = "80"
	}
	addr, err := net.ResolveUDPAddr("udp", net.JoinHostPort(host, port))
	if err != nil {
		return StatusInvalid, nil
	}
	conn, err := net.DialUDP("udp", nil, addr)
	if err != nil {
		return StatusDead, nil
	}
	defer conn.Close()
	conn.SetDeadline(time.Now().Add(defaultTimeout))

	connectionID := uint64(0x41727101980)
	action := uint32(0)
	transID := uint32(randomInt(0, 0xFFFFFFFF))
	packet := make([]byte, 16)
	bigEndianPutUint64(packet[0:8], connectionID)
	bigEndianPutUint32(packet[8:12], action)
	bigEndianPutUint32(packet[12:16], transID)

	start := time.Now()
	if _, err := conn.Write(packet); err != nil {
		return StatusDead, nil
	}
	response := make([]byte, 16)
	n, err := conn.Read(response)
	if err != nil {
		return StatusDead, nil
	}
	elapsed := int64(time.Since(start).Milliseconds())
	if n >= 8 {
		return StatusAlive, &elapsed
	}
	return StatusAlive, &elapsed
}

func bigEndianPutUint64(b []byte, v uint64) {
	b[0] = byte(v >> 56)
	b[1] = byte(v >> 48)
	b[2] = byte(v >> 40)
	b[3] = byte(v >> 32)
	b[4] = byte(v >> 24)
	b[5] = byte(v >> 16)
	b[6] = byte(v >> 8)
	b[7] = byte(v)
}

func bigEndianPutUint32(b []byte, v uint32) {
	b[0] = byte(v >> 24)
	b[1] = byte(v >> 16)
	b[2] = byte(v >> 8)
	b[3] = byte(v)
}

func randomInt(min, max int) int {
	n, _ := rand.Int(rand.Reader, big.NewInt(int64(max-min)))
	return int(n.Int64()) + min
}

func checkWSS(ctx context.Context, tracker string) (string, *int64) {
	dialer := websocket.Dialer{
		HandshakeTimeout: defaultTimeout,
	}
	start := time.Now()
	conn, _, err := dialer.DialContext(ctx, tracker, nil)
	if err != nil {
		return StatusDead, nil
	}
	defer conn.Close()
	elapsed := int64(time.Since(start).Milliseconds())
	return StatusAlive, &elapsed
}

func validateTracker(ctx context.Context, tracker string) CheckResult {
	u, err := url.Parse(tracker)
	if err != nil {
		return CheckResult{URL: tracker, Status: StatusInvalid}
	}
	scheme := strings.ToLower(u.Scheme)
	var status string
	var ping *int64
	switch scheme {
	case "http", "https":
		status, ping = checkHTTP(ctx, tracker)
	case "udp":
		status, ping = checkUDP(ctx, tracker)
	case "wss":
		status, ping = checkWSS(ctx, tracker)
	default:
		status = StatusInvalid
	}
	return CheckResult{URL: tracker, Status: status, PingMs: ping}
}

func loadTrackers(filepath string) ([]string, error) {
	f, err := os.Open(filepath)
	if err != nil {
		return nil, fmt.Errorf("error reading %s: %v", filepath, err)
	}
	defer f.Close()

	content, err := io.ReadAll(f)
	if err != nil {
		return nil, err
	}
	text := strings.ReplaceAll(string(content), ",", "\n")

	var trackers []string
	seen := map[string]bool{}
	scanner := bufio.NewScanner(strings.NewReader(text))
	for scanner.Scan() {
		line := scanner.Text()
		parsed := parseTrackerLine(line)
		if parsed == "" || strings.HasPrefix(parsed, "#") {
			continue
		}
		matches := trackerRe.FindAllString(parsed, -1)
		for _, match := range matches {
			norm, err := normalizeTrackerURL(match)
			if err != nil {
				continue
			}
			if !seen[norm] {
				seen[norm] = true
				trackers = append(trackers, norm)
			}
		}
	}
	return trackers, scanner.Err()
}

func filterBlacklist(trackers []string, blFile string) []string {
	if _, err := os.Stat(blFile); os.IsNotExist(err) {
		return trackers
	}
	f, err := os.Open(blFile)
	if err != nil {
		return trackers
	}
	defer f.Close()
	var patterns []string
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		patterns = append(patterns, line)
	}
	if len(patterns) == 0 {
		return trackers
	}
	filtered := make([]string, 0, len(trackers))
	for _, t := range trackers {
		exclude := false
		for _, p := range patterns {
			if strings.Contains(t, p) {
				exclude = true
				break
			}
		}
		if !exclude {
			filtered = append(filtered, t)
		}
	}
	return filtered
}

func sortUnique(items []string) []string {
	m := make(map[string]bool, len(items))
	for _, item := range items {
		m[item] = true
	}
	unique := make([]string, 0, len(m))
	for item := range m {
		unique = append(unique, item)
	}
	sort.Strings(unique)
	return unique
}

func writeLines(path string, lines []string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	for _, line := range lines {
		fmt.Fprintln(f, line)
	}
	return nil
}

func loadHistory(path string) (map[string]*TrackerHistory, error) {
	hist := map[string]*TrackerHistory{}
	f, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			return hist, nil
		}
		return nil, err
	}
	defer f.Close()
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.Split(line, "\t")
		if len(parts) < 7 {
			continue
		}
		var h TrackerHistory
		if v, err := strconv.ParseUint(parts[1], 10, 64); err == nil {
			h.Checks = v
		}
		if v, err := strconv.ParseUint(parts[2], 10, 64); err == nil {
			h.AliveChecks = v
		}
		if v, err := strconv.ParseInt(parts[3], 10, 64); err == nil {
			h.FirstSeenTs = v
		}
		if v, err := strconv.ParseInt(parts[4], 10, 64); err == nil {
			h.FirstAliveTs = v
		}
		if v, err := strconv.ParseInt(parts[5], 10, 64); err == nil {
			h.LastSeenTs = v
		}
		if v, err := strconv.ParseInt(parts[6], 10, 64); err == nil {
			h.LastAliveTs = v
		}
		if len(parts) >= 8 {
			if v, err := strconv.ParseInt(parts[7], 10, 64); err == nil {
				h.StreakAliveStartTs = v
			}
		} else if h.LastSeenTs != 0 && h.LastSeenTs == h.LastAliveTs {
			h.StreakAliveStartTs = h.LastSeenTs
		}
		hist[parts[0]] = &h
	}
	return hist, scanner.Err()
}

func saveHistory(path string, hist map[string]*TrackerHistory) error {
	urls := make([]string, 0, len(hist))
	for u := range hist {
		urls = append(urls, u)
	}
	sort.Strings(urls)
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	for _, u := range urls {
		h := hist[u]
		fmt.Fprintf(f, "%s\t%d\t%d\t%d\t%d\t%d\t%d\t%d\n",
			u, h.Checks, h.AliveChecks, h.FirstSeenTs, h.FirstAliveTs, h.LastSeenTs, h.LastAliveTs, h.StreakAliveStartTs)
	}
	return nil
}

func updateHistory(hist map[string]*TrackerHistory, results []CheckResult, nowTs int64) {
	for _, r := range results {
		entry, exists := hist[r.URL]
		if !exists {
			entry = &TrackerHistory{}
			hist[r.URL] = entry
		}
		wasAliveLast := entry.LastSeenTs != 0 && entry.LastSeenTs == entry.LastAliveTs
		entry.Checks++
		if entry.FirstSeenTs == 0 {
			entry.FirstSeenTs = nowTs
		}
		entry.LastSeenTs = nowTs

		if r.Status == StatusAlive {
			if !wasAliveLast || entry.StreakAliveStartTs == 0 {
				entry.StreakAliveStartTs = nowTs
			}
			entry.AliveChecks++
			if entry.FirstAliveTs == 0 {
				entry.FirstAliveTs = nowTs
			}
			entry.LastAliveTs = nowTs
		} else {
			entry.StreakAliveStartTs = 0
		}
	}
}

func getProtocol(u string) string {
	parsed, err := url.Parse(u)
	if err != nil {
		return "other"
	}
	return parsed.Scheme
}

func main() {
	input := flag.String("input", "merged_trackers.txt", "Input file with raw tracker URLs")
	output := flag.String("output", "trackers_best.txt", "File to write best (alive) trackers")
	workers := flag.Int("workers", defaultWorkers, "Number of concurrent workers")
	flag.Parse()

	inputFile := *input
	outputFile := *output
	concurrency := *workers
	if concurrency < 1 {
		concurrency = defaultWorkers
	}

	// Load
	trackers, err := loadTrackers(inputFile)
	if err != nil {
		log.Fatalf("Failed to load trackers: %v", err)
	}
	trackers = filterBlacklist(trackers, "blackstr.txt")
	allTrackers := sortUnique(trackers)
	if len(allTrackers) == 0 {
		log.Fatal("No valid trackers found.")
	}

	outputDir := filepath.Dir(outputFile)
	if err := writeLines(filepath.Join(outputDir, "trackers_all.txt"), allTrackers); err != nil {
		log.Fatalf("Error writing trackers_all.txt: %v", err)
	}

	// Concurrency
	sem := make(chan struct{}, concurrency)
	var wg sync.WaitGroup
	var resultsLock sync.Mutex
	results := make([]CheckResult, 0, len(allTrackers))

	var completed int32
	total := len(allTrackers)
	startTime := time.Now()
	ctx := context.Background()

	for _, tracker := range allTrackers {
		wg.Add(1)
		go func(t string) {
			defer wg.Done()
			sem <- struct{}{}
			defer func() { <-sem }()

			res := validateTracker(ctx, t)
			resultsLock.Lock()
			results = append(results, res)
			resultsLock.Unlock()

			done := atomic.AddInt32(&completed, 1)
			fmt.Printf("[%d/%d] %s %s\n", done, total, res.Status, res.URL)
		}(tracker)
	}
	wg.Wait()
	close(sem)

	// Summarize
	var aliveList []string
	var deadCount, invalidCount int
	for _, r := range results {
		switch r.Status {
		case StatusAlive:
			aliveList = append(aliveList, r.URL)
		case StatusDead:
			deadCount++
		case StatusInvalid:
			invalidCount++
		}
	}
	aliveList = sortUnique(aliveList)

	// Write best files
	if err := writeLines(outputFile, aliveList); err != nil {
		log.Fatalf("Error writing %s: %v", outputFile, err)
	}
	for _, proto := range []string{"http", "https", "udp", "wss"} {
		var urls []string
		for _, u := range aliveList {
			if getProtocol(u) == proto {
				urls = append(urls, u)
			}
		}
		writeLines(filepath.Join(outputDir, "trackers_best_"+proto+".txt"), sortUnique(urls))
	}

	// History
	historyPath := filepath.Join(outputDir, "tracker_history.tsv")
	history, err := loadHistory(historyPath)
	if err != nil {
		log.Fatalf("Failed to load history: %v", err)
	}
	nowTs := time.Now().Unix()
	updateHistory(history, results, nowTs)
	if err := saveHistory(historyPath, history); err != nil {
		log.Fatalf("Failed to save history: %v", err)
	}

	elapsed := time.Since(startTime).Round(time.Millisecond)
	fmt.Printf("Checked %d trackers in %s. Alive: %d, Dead: %d, Invalid: %d\n",
		len(results), elapsed, len(aliveList), deadCount, invalidCount)
}