#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Tracker 检查器 - 生成 Markdown 文档 + MkDocs 兼容
用法: python tracker_checker.py <输入文件> <输出最佳列表文件> [--workers N] [--generate-docs]
"""

import argparse
import os
import re
import random
import socket
import sys
import time
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional, Dict, Tuple
from urllib.parse import urlparse, ParseResult, urlunparse

import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

# ----------------------------------------------------------------------
# 常量
DEFAULT_TIMEOUT = 10          # 秒
DEFAULT_WORKERS = 20
OUTPUT_FILES = [
    "trackers_all.txt",
    "trackers_best.txt",
    "trackers_best_http.txt",
    "trackers_best_https.txt",
    "trackers_best_udp.txt",
    "trackers_best_wss.txt",
]

# ----------------------------------------------------------------------
class Status:
    ALIVE = "ALIVE"
    DEAD = "DEAD"
    INVALID = "INVALID"

# ----------------------------------------------------------------------
@dataclass
class CheckResult:
    url: str
    status: str
    ping_ms: Optional[int] = None

@dataclass
class TrackerHistory:
    checks: int = 0
    alive_checks: int = 0
    first_seen_ts: int = 0
    first_alive_ts: int = 0
    last_seen_ts: int = 0
    last_alive_ts: int = 0
    streak_alive_start_ts: int = 0

# ----------------------------------------------------------------------
def parse_tracker_line(line: str) -> str:
    line = line.strip()
    if line.startswith('[') and '](' in line and line.endswith(')'):
        _, _, right = line.partition('](')
        return right[:-1]
    return line

TRACKER_REGEX = re.compile(r'(?i)(https?|udp|wss)://[^\s,]*?/announce')

def collapse_path_slashes(path: str) -> str:
    result = []
    prev = False
    for ch in path:
        if ch == '/':
            if not prev:
                result.append(ch)
            prev = True
        else:
            result.append(ch)
            prev = False
    out = ''.join(result)
    return '/' if out == '' else out

def normalize_tracker_url(raw: str) -> Optional[str]:
    candidate = raw.strip().strip('\'"<>[](){};,.')

    try:
        parsed = urlparse(candidate)
    except ValueError:
        return None

    scheme = parsed.scheme.lower()
    if scheme not in ('http', 'https', 'udp', 'wss'):
        return None

    host = parsed.hostname
    if not host:
        return None

    try:
        socket.inet_aton(host)
        is_ip = True
    except OSError:
        is_ip = False
    if not is_ip and '.' not in host:
        return None

    path = collapse_path_slashes(parsed.path)
    if not path.endswith('/announce'):
        return None

    new_parsed = ParseResult(
        scheme=scheme,
        netloc=parsed.netloc,
        path=path,
        params='',
        query='',
        fragment=''
    )

    if (scheme == 'http' and parsed.port == 80) or (scheme == 'https' and parsed.port == 443):
        new_parsed = new_parsed._replace(netloc=host)

    return urlunparse(new_parsed)

def bdecode_simple(data: bytes) -> bool:
    if not data or data[0] != ord('d'):
        return False
    return any(kw in data for kw in (b'interval', b'peers', b'failure reason'))

def is_parked_or_expired_domain(content: bytes) -> bool:
    text = content.decode('utf-8', errors='replace').lower()
    indicators = [
        "domain for sale", "domain is for sale", "buy this domain",
        "domain expired", "domain has expired", "this domain is expired",
        "register this domain", "domain available", "parked domain",
        "domain parking", "coming soon", "under construction",
        "page not found", "404 not found", "namecheap",
        "godaddy parked", "sedo domain parking", "domain portfolio",
        "premium domain", "afternic", "escrow.com", "dan.com/buy-domain",
        "undeveloped", "this webpage was generated by the domain owner",
        "hugedomains.com", "bodis.com", "sedoparking"
    ]
    if any(ind in text for ind in indicators):
        return True
    head = content[:500].decode('utf-8', errors='replace').lower()
    return '<html' in head or '<!doctype html' in head

# ----------------------------------------------------------------------
def check_http_tracker(url: str, timeout: int) -> Tuple[str, Optional[int]]:
    session = requests.Session()
    retries = Retry(total=0, connect=0, read=0, redirect=0)
    adapter = HTTPAdapter(max_retries=retries)
    session.mount('http://', adapter)
    session.mount('https://', adapter)

    peer_id_random = ''.join(str(random.randint(0, 9)) for _ in range(12))
    peer_id = f"-RS0001-{peer_id_random}"
    params = {
        'info_hash': '00000000000000000000',
        'peer_id': peer_id,
        'port': '6881',
        'uploaded': '0',
        'downloaded': '0',
        'left': '0',
        'compact': '1',
        'event': 'started'
    }

    try:
        start = time.time()
        resp = session.get(url, params=params, timeout=timeout, allow_redirects=False)
        elapsed = int((time.time() - start) * 1000)
    except Exception:
        return Status.DEAD, None

    body = resp.content

    if is_parked_or_expired_domain(body):
        return Status.INVALID, elapsed

    if bdecode_simple(body):
        return Status.ALIVE, elapsed

    if resp.status_code == 200:
        head = body[:200].decode('utf-8', errors='replace').lower()
        if any(tag in head for tag in ('<html', '<body', '<head')):
            return Status.INVALID, elapsed
        if len(body) > 50000:
            return Status.INVALID, elapsed
        return Status.DEAD, elapsed

    if resp.status_code in (400, 403) and bdecode_simple(body):
        return Status.ALIVE, elapsed

    return Status.DEAD, elapsed

def check_udp_tracker(url: str, timeout: int) -> Tuple[str, Optional[int]]:
    try:
        parsed = urlparse(url)
        host = parsed.hostname
        port = parsed.port or 80
    except ValueError:
        return Status.INVALID, None

    if not host:
        return Status.INVALID, None

    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        sock.settimeout(timeout)
    except OSError:
        return Status.DEAD, None

    conn_id = 0x41727101980
    action = 0
    trans_id = random.randint(0, 0xFFFFFFFF)
    packet = conn_id.to_bytes(8, 'big') + action.to_bytes(4, 'big') + trans_id.to_bytes(4, 'big')

    try:
        start = time.time()
        sock.sendto(packet, (host, port))
        data, _ = sock.recvfrom(16)
        elapsed = int((time.time() - start) * 1000)
        return Status.ALIVE, elapsed
    except OSError:
        return Status.DEAD, None
    finally:
        sock.close()

def check_wss_tracker(url: str, timeout: int) -> Tuple[str, Optional[int]]:
    try:
        parsed = urlparse(url)
        host = parsed.hostname
        port = parsed.port or 443
    except ValueError:
        return Status.INVALID, None

    if not host:
        return Status.INVALID, None

    try:
        start = time.time()
        sock = socket.create_connection((host, port), timeout=timeout)
        sock.close()
        elapsed = int((time.time() - start) * 1000)
        return Status.ALIVE, elapsed
    except OSError:
        return Status.DEAD, None

def validate_tracker(url: str, timeout: int) -> CheckResult:
    try:
        parsed = urlparse(url)
    except ValueError:
        return CheckResult(url, Status.INVALID)

    scheme = parsed.scheme.lower()
    if scheme in ('http', 'https'):
        status, ping = check_http_tracker(url, timeout)
    elif scheme == 'udp':
        status, ping = check_udp_tracker(url, timeout)
    elif scheme == 'wss':
        status, ping = check_wss_tracker(url, timeout)
    else:
        status, ping = Status.INVALID, None

    return CheckResult(url, status, ping)

# ----------------------------------------------------------------------
def dedupe_keep_order(items: List[str]) -> List[str]:
    seen = set()
    out = []
    for i in items:
        if i not in seen:
            seen.add(i)
            out.append(i)
    return out

def sort_unique(items: List[str]) -> List[str]:
    return sorted(set(items))

def load_trackers(filepath: str) -> List[str]:
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            text = f.read()
    except FileNotFoundError:
        print(f"❌ 错误：文件 {filepath} 未找到")
        sys.exit(1)

    text = text.replace(',', '\n')
    trackers = []
    for line in text.splitlines():
        parsed = parse_tracker_line(line)
        if not parsed or parsed.startswith('#'):
            continue
        for m in TRACKER_REGEX.finditer(parsed):
            norm = normalize_tracker_url(m.group())
            if norm:
                trackers.append(norm)

    return dedupe_keep_order(trackers)

def filter_blacklist(trackers: List[str], blacklist_file: str = "blackstr.txt") -> List[str]:
    if not os.path.isfile(blacklist_file):
        return trackers
    with open(blacklist_file, 'r', encoding='utf-8') as f:
        patterns = [line.strip() for line in f if line.strip() and not line.startswith('#')]
    if not patterns:
        return trackers
    return [t for t in trackers if not any(p in t for p in patterns)]

def write_lines(path: Path, lines: List[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + ('\n' if lines else ''))

def delete_old_outputs(output_dir: Path, filenames: List[str]) -> None:
    for fname in filenames:
        filepath = output_dir / fname
        if filepath.exists():
            filepath.unlink()
            print(f"🗑️  已删除旧文件: {filepath}")

# ----------------------------------------------------------------------
def load_history(path: Path) -> Dict[str, TrackerHistory]:
    history = {}
    if not path.is_file():
        return history
    with open(path, 'r', encoding='utf-8') as f:
        for line in f:
            parts = line.strip().split('\t')
            if len(parts) not in (7, 8):
                continue
            try:
                url = parts[0]
                vals = list(map(int, parts[1:]))
                if len(vals) == 7:
                    streak = vals[6] if (vals[4] != 0 and vals[4] == vals[5]) else 0
                else:
                    streak = vals[7]
                history[url] = TrackerHistory(
                    checks=vals[0],
                    alive_checks=vals[1],
                    first_seen_ts=vals[2],
                    first_alive_ts=vals[3],
                    last_seen_ts=vals[4],
                    last_alive_ts=vals[5],
                    streak_alive_start_ts=streak
                )
            except (ValueError, IndexError):
                continue
    return history

def save_history(path: Path, history: Dict[str, TrackerHistory]) -> None:
    urls = sorted(history.keys())
    with open(path, 'w', encoding='utf-8') as f:
        for url in urls:
            h = history[url]
            f.write(f"{url}\t{h.checks}\t{h.alive_checks}\t"
                    f"{h.first_seen_ts}\t{h.first_alive_ts}\t"
                    f"{h.last_seen_ts}\t{h.last_alive_ts}\t"
                    f"{h.streak_alive_start_ts}\n")

def update_history(history: Dict[str, TrackerHistory],
                   results: List[CheckResult], now_ts: int) -> None:
    for r in results:
        entry = history.setdefault(r.url, TrackerHistory())
        was_alive_last_run = (entry.last_seen_ts != 0 and
                              entry.last_seen_ts == entry.last_alive_ts)
        entry.checks += 1
        if entry.first_seen_ts == 0:
            entry.first_seen_ts = now_ts
        entry.last_seen_ts = now_ts

        if r.status == Status.ALIVE:
            if not was_alive_last_run or entry.streak_alive_start_ts == 0:
                entry.streak_alive_start_ts = now_ts
            entry.alive_checks += 1
            if entry.first_alive_ts == 0:
                entry.first_alive_ts = now_ts
            entry.last_alive_ts = now_ts
        else:
            entry.streak_alive_start_ts = 0

# ----------------------------------------------------------------------
def get_protocol(url: str) -> str:
    try:
        return urlparse(url).scheme
    except ValueError:
        return "other"

def html_escape(text: str) -> str:
    return text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;').replace('"', '&quot;')

def generate_docs_markdown(results: List[CheckResult], history: Dict[str, TrackerHistory],
                           input_file: str, output_file: str) -> None:
    """生成 Markdown 文档以及 tracker 列表文件，适配 MkDocs"""
    docs_dir = Path("docs")
    docs_dir.mkdir(exist_ok=True)

    total = len(results)
    alive_list = [r for r in results if r.status == Status.ALIVE]
    dead_count = sum(1 for r in results if r.status == Status.DEAD)
    invalid_count = sum(1 for r in results if r.status == Status.INVALID)
    alive_count = len(alive_list)
    uptime_pct = (alive_count * 100 / total) if total else 0

    now_ts = int(time.time())
    last_update = time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime(now_ts))

    alive_by_proto = defaultdict(list)
    for r in alive_list:
        proto = get_protocol(r.url)
        if proto in ('http', 'https', 'udp', 'wss'):
            alive_by_proto[proto].append(r.url)

    # 写出 tracker 列表文件（供下载）
    write_lines(docs_dir / "trackers_best.txt", sort_unique([r.url for r in alive_list]))
    for proto in ('http', 'https', 'udp', 'wss'):
        write_lines(docs_dir / f"trackers_best_{proto}.txt", sort_unique(alive_by_proto[proto]))

    # ---------- 构建 Markdown 首页 ----------
    index_md = f"""# Tracker 状态仪表盘

**输入文件**: `{html_escape(input_file)}`  
**输出文件**: `{html_escape(output_file)}`  
**最后更新**: {last_update}

[公开统计](public-stats/index.md)

## 统计摘要

| 指标 | 数值 |
|------|------|
| 总检测数 | {total} |
| 🟢 在线 | {alive_count} |
| 🔴 死亡 | {dead_count} |
| ⚠️ 无效 | {invalid_count} |
| 全局限存活率 | {uptime_pct:.2f}% |
| HTTP / HTTPS / UDP / WSS | {len(alive_by_proto['http'])} / {len(alive_by_proto['https'])} / {len(alive_by_proto['udp'])} / {len(alive_by_proto['wss'])} |

## 快速下载

- [所有存活 tracker](trackers_best.txt)
- [HTTP](trackers_best_http.txt) · [HTTPS](trackers_best_https.txt) · [UDP](trackers_best_udp.txt) · [WSS](trackers_best_wss.txt)

## 详细状态

| 状态 | URL | 延迟 | 在线率 | 连续在线天数 |
|------|-----|------|--------|-------------|
"""

    sorted_results = sorted(results, key=lambda r: (
        0 if r.status == Status.ALIVE else (1 if r.status == Status.DEAD else 2),
        r.url
    ))

    for r in sorted_results:
        status_emoji = {'ALIVE': '🟢', 'DEAD': '🔴', 'INVALID': '⚠️'}.get(r.status, '❓')
        status_text = {'ALIVE': '在线', 'DEAD': '死亡', 'INVALID': '无效'}.get(r.status, r.status)
        ping_text = f"{r.ping_ms} ms" if r.ping_ms else "-"
        h = history.get(r.url, TrackerHistory())
        uptime = (h.alive_checks * 100 / h.checks) if h.checks else 0
        days = 0
        if r.status == Status.ALIVE and h.streak_alive_start_ts and h.streak_alive_start_ts != 0:
            days = (now_ts - h.streak_alive_start_ts) // 86400 + 1
        url_safe = html_escape(r.url)
        index_md += f"| {status_emoji} {status_text} | [{url_safe}]({url_safe}) | {ping_text} | {uptime:.2f}% | {days} |\n"

    (docs_dir / "index.md").write_text(index_md, encoding='utf-8')

    # public-stats/index.md
    public_stats_dir = docs_dir / "public-stats"
    public_stats_dir.mkdir(exist_ok=True)
    public_stats_md = f"""# 公开统计

- **检测总数**: {total}
- **在线**: {alive_count}
- **存活率**: {uptime_pct:.2f}%
- **更新时间戳**: {now_ts}

[返回仪表盘](../index.md)
"""
    (public_stats_dir / "index.md").write_text(public_stats_md, encoding='utf-8')

    print("✅ 已生成 docs/ 下的 Markdown 文件和 tracker 列表文件。")

# ----------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(description='Tracker 状态检查器')
    parser.add_argument('input', help='合并后的输入文件')
    parser.add_argument('output', help='最佳存活 tracker 输出文件 (trackers_best.txt)')
    parser.add_argument('--workers', type=int, default=DEFAULT_WORKERS, help='并行线程数')
    parser.add_argument('--generate-docs', action='store_true', help='生成 Markdown 文档（MkDocs）')
    args = parser.parse_args()

    input_file = args.input
    output_file = args.output
    workers = max(1, args.workers)

    output_dir = Path(output_file).resolve().parent

    print("=" * 60)
    print("🚀 Tracker 检查器 - Markdown 输出模式")
    print(f"📄 输入: {input_file}")
    print(f"📁 输出目录: {output_dir}")
    print(f"⚙️  并行线程: {workers}")
    print("=" * 60)

    trackers = load_trackers(input_file)
    trackers = filter_blacklist(trackers)
    all_trackers = sort_unique(trackers)

    if not all_trackers:
        print("❌ 没有有效的 tracker，退出。")
        sys.exit(1)

    print(f"\n📋 共收集到 {len(all_trackers)} 个 tracker，开始检查...\n")

    # 删除旧的输出文件（可选）
    delete_old_outputs(output_dir, OUTPUT_FILES + ["tracker_history.tsv"])

    # 写出全部 tracker
    write_lines(output_dir / "trackers_all.txt", all_trackers)

    timeout = DEFAULT_TIMEOUT
    results: List[CheckResult] = []
    alive_results: List[CheckResult] = []
    dead_count = 0
    invalid_count = 0
    completed = 0
    total = len(all_trackers)

    def worker(tracker: str) -> CheckResult:
        nonlocal completed
        res = validate_tracker(tracker, timeout)
        completed += 1
        status_cn = {'ALIVE': '存活', 'DEAD': '死亡', 'INVALID': '无效'}.get(res.status, '?')
        print(f"[{completed:4d}/{total}] {status_cn} {res.url}")
        return res

    with ThreadPoolExecutor(max_workers=workers) as executor:
        future_to_url = {executor.submit(worker, url): url for url in all_trackers}
        for future in as_completed(future_to_url):
            try:
                res = future.result()
                results.append(res)
                if res.status == Status.ALIVE:
                    alive_results.append(res)
                elif res.status == Status.DEAD:
                    dead_count += 1
                else:
                    invalid_count += 1
            except Exception as e:
                print(f"⚠️  线程异常: {e}")

    # 写最佳文件及按协议分类
    best_urls = sort_unique([r.url for r in alive_results])
    write_lines(output_dir / "trackers_best.txt", best_urls)

    alive_by_proto = defaultdict(list)
    for url in best_urls:
        proto = get_protocol(url)
        if proto in ('http', 'https', 'udp', 'wss'):
            alive_by_proto[proto].append(url)

    for proto in ('http', 'https', 'udp', 'wss'):
        write_lines(output_dir / f"trackers_best_{proto}.txt", sort_unique(alive_by_proto[proto]))

    # 历史记录
    history_path = output_dir / "tracker_history.tsv"
    history = load_history(history_path)
    now_ts = int(time.time())
    update_history(history, results, now_ts)
    save_history(history_path, history)

    # 生成 Markdown 文档（如果指定）
    if args.generate_docs:
        print("\n📄 正在生成 Markdown 文档和 tracker 列表文件...")
        generate_docs_markdown(results, history, input_file, output_file)

    # 最终统计
    print("\n" + "=" * 60)
    print("✅ 检查完成！")
    print(f"   🔹 存活: {len(alive_results)}")
    print(f"   🔸 死亡: {dead_count}")
    print(f"   🔻 无效: {invalid_count}")
    print(f"   📦 全部: {total}")
    print(f"   📁 文件位置: {output_dir}")
    for fname in OUTPUT_FILES:
        full_path = output_dir / fname
        if full_path.exists():
            print(f"   📄 {fname}")
    if args.generate_docs:
        print(f"   🌐 文档: docs/ 目录（Markdown 文件）")

if __name__ == '__main__':
    main()